### ISSUE TITLE
SystemUI and Process System isn't reponding

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [PixelOS-Devices-old/device_xiaomi_gauguin#1]
This problem found after [PixelOS March update](https://blog.pixelos.net/blogs/2024-04-16-April-Update), before this update my phone haven't found this problem anytime
I found this error on my phone always in deep sleep mode (like I woke up my phone after 3 hours), while it wake up, **the first problem is screen refresh Hz get error, it will be really stuck and lag;** Then I open a APP on my phone, the SystemUI and Process System will no reponding, sometimes it's SystemUI crash, sometimes it's Process System crash; And if I choose wait for respond, my APP **will no reponding with Process System**, for now I can restart my phone to deal this problem but it will happend gagin; my system logs are here, if anyone want more info just reply me
Anyway, thanks for your support😊
[Log_2024-05-21_12-27-11.txt](https://github.com/PixelOS-Devices/device_xiaomi_gauguin/files/15384525/Log_2024-05-21_12-27-11.txt)

**Comment by xiaoyueyoqwq** [comment]
This is another crash logs I found it on my phone, maybe it can help
[crash_20240521.txt](https://github.com/PixelOS-Devices/device_xiaomi_gauguin/files/15384559/crash_20240521.txt)

**Comment by hridaya2004** [comment]
Any way to reproduce the issue?
Also what is APP here?
Are you using any modules or stuffs?

**Comment by xiaoyueyoqwq** [comment]
> Any way to reproduce the issue?
> Also what is APP here?
> Are you using any modules or stuffs?

Reproduced: Opening an APP can make your phone lag and switch to another APP can make your phone lag, then you may find you cannot go back to the desktop, wait for a few seconds then you can see the SystemUI no responding

APPs: idk what APP can 100% reproduce this problem but maybe some lag APP can reproduce it(eg. WeChat and Edge)

Modules: yes I used some modules, but I don't use any modules like Optimizing CPU scheduling/memory, etc. may involve modifying modules of the underlying system logic, here is modules list

![Screenshot_20240526-022810.png](https://github.com/PixelOS-Devices/device_xiaomi_gauguin/assets/71379165/b034c540-dcdb-4192-980b-577dee2538d7)

![Screenshot_20240526-022814.png](https://github.com/PixelOS-Devices/device_xiaomi_gauguin/assets/71379165/e3aa1003-f610-458e-82bd-d17f1ab06acd)

![Screenshot_20240526-022819.png](https://github.com/PixelOS-Devices/device_xiaomi_gauguin/assets/71379165/aa72b5bd-5aaf-4e64-a56b-5a4d8e6dcdc2)

**Comment by hridaya2004** [comment]
Remove "ALL" those Magisk modules and check again.
FYI: I don't have such issues on my device.

**Comment by xiaoyueyoqwq** [comment]
> Remove "ALL" those Magisk modules and check again.
> FYI: I don't have such issues on my device.

It is indeed difficult to reproduce this problem in some cases, because this problem is already a "metaphysical" problem; the only information I can provide at present is to try to trigger this bug after using your phone for more than two days in a row. During use, if you leave your phone for a long time and then unlock it immediately and open some apps that may cause the phone to freeze, there is a high probability that this bug will be triggered; therefore, I still recommend that you look at the log to analyze this problem

About the magisk module problem, I have already tested on my phone, just wait for the answer

**Comment by hridaya2004** [comment]
> after using your phone for more than two days in a row. 

I am already using the device with more than 144hr uptime, and have faced no such issues

> leave your phone for a long time and then unlock it immediately and open some apps that may cause the phone to freeze, there is a high probability that this bug will be triggered

I do usually leave the device idle for 6-8 hours a day.

**Comment by hridaya2004** [comment]
Probably try doing a clean flash? :/

**Comment by hridaya2004** [comment]
Also, closing this issue.
You can message me further in Telegram regarding this issue.

**Comment by xiaoyueyoqwq** [comment]
> Probably try doing a clean flash? :/

none that's not work, I tred clean flash three times ;<
