### ISSUE TITLE
[CRASH] Device SystemUI crash *again*

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [PixelOS-Devices-old/device_xiaomi_gauguin#2]
I notice the PixelOS Aug update already fixed the SystemUI crash's problem, but the turly things is it still happend on my device; when my device working after 20h later it will happend and I only can used restart device to sloved it, here is the verbos [crash report](https://wormhole.app/P7ONn#-nrqmbnUuOkYtApQX95yug)

ATTATION: for my device security and privacy, this logs will be deleted after 24h so plz download it on your PC

**Comment by hridaya2004** [comment]
We already have had talks regarding this.
